version: '3.4'

services:
  service.database:
    image: postgres:latest
    container_name: service.database
    environment:
    - POSTGRES_DB=rating_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456 
    volumes:
    - ./.containers/rating_db-db:/var/lib/postgresql/data
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  notificationservice.api:
    image: ${DOCKER_REGISTRY-}notificationserviceapi
    build:
      context: .
      dockerfile: NotificationService.Api/Dockerfile
    ports:
    - "5000:5000"
  ratingservice.api:
    image: ${DOCKER_REGISTRY-}ratingserviceapi
    build:
      context: .
      dockerfile: RatıngService.Api/Dockerfile
    ports:
    - "6000:6000"
    depends_on: 
     service.database:
      condition: service_healthy

  
