// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatingService.Dal.DbContexts;

#nullable disable

namespace RatingService.Dal.Migrations
{
    [DbContext(typeof(PostgreDbContext))]
    [Migration("20240507184142_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatingService.Entities.ProviderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9269),
                            Name = "Ilyas",
                            Surname = "Salman"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9270),
                            Name = "Adile",
                            Surname = "Nasit"
                        });
                });

            modelBuilder.Entity("RatingService.Entities.RatingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Point")
                        .HasColumnType("double precision");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9078),
                            Point = 4.5,
                            ProviderId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9081),
                            Point = 5.0,
                            ProviderId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9082),
                            Point = 3.0,
                            ProviderId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9084),
                            Point = 3.5,
                            ProviderId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9085),
                            Point = 2.5,
                            ProviderId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9086),
                            Point = 4.5,
                            ProviderId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9087),
                            Point = 5.0,
                            ProviderId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9089),
                            Point = 3.0,
                            ProviderId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9090),
                            Point = 3.5,
                            ProviderId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9091),
                            Point = 2.5,
                            ProviderId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("RatingService.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9242),
                            Name = "Abuzer",
                            Surname = "Kadayif"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 7, 18, 41, 42, 11, DateTimeKind.Utc).AddTicks(9243),
                            Name = "Temel",
                            Surname = "Reis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
